MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_fcos_efficientnet_fpn_backbone"
    FREEZE_AT: 0
  SIMPLENET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
    OUT_CHANNELS: 128
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    POST_NMS_TOPK_TEST: 50
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
  MASK_ON: True
  MASKIOU_ON: True
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 2
    CONV_DIM: 128
  ROI_MASKIOU_HEAD:
    NUM_CONV: 2
    CONV_DIM: 128
DATASETS:
  TRAIN: ("openimages_train",)
  TEST: ()
SOLVER:
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025  
  STEPS: (60000, 80000)
  MAX_ITER: 120000
INPUT:
  MIN_SIZE_TRAIN: (580, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000